events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    client_max_body_size 10M;

    upstream web_api_backend {
        server culinary_api:8080;
    }

    server {
        listen 80;
        server_name localhost;

        # 1. Снимки / Uploads
        location /uploads/ {
            alias /usr/share/nginx/html/uploads/;
            expires 30d;
            add_header Cache-Control "public, no-transform";
        }

        # 2. C# Web API заявки
        location /api/ {
            proxy_pass http://web_api_backend;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection keep-alive;
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # 3. Swagger UI
        location /swagger/ {
            proxy_pass http://web_api_backend/swagger/;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
        }

        # 4. React / Vue SPA маршрутизиране (Всичко останало)
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }
    }
}